### PR TITLE
Update AmazonOrderItemLIst

### PR DESCRIPTION
**Pull request by michalmagic42**
+ Provide ProductInfo details
+ Provide NumberOfItems from ProductInfo

### CODE REVIEW

**Comment by michalmagic42** [comment]
Please look at the MR and merge with the new release tag if approved. Thank you.

**Comment by georanma** [comment]
Hi Michal,

Should have time to review this week.

**Comment by michalmagic42** [comment]
Thanks George.

**Comment by michalmagic42** [comment]
Any info George?

**Comment by georanma** [comment]
Hi Michal,

Should have an answer later today.

**Comment by michalmagic42** [comment]
Any update on this George?

**Comment by georanma** [comment]
@michalmagic42 released and tagged

**Pull request merged**
