### PR TITLE
Update \Georanma\AmazonMws\AmazonInventoryList::parseXML

### PR DESCRIPTION
**Pull request by michalmagic42**
+ parse supplylist supplydetails only when they are included in response xml

+ preventing undefined node

### CODE REVIEW

**Comment by michalmagic42** [comment]
@georanma could you please look at this PR, if you accept and merge please create also a release tag

**Comment by georanma** [comment]
Ill take a look asap and let you know.

**Comment by Ig0r-M-magic42** [comment]
@georanma any ETA ?

**Comment by georanma** [comment]
@Ig0r-M merged and tagged

**Pull request merged**
