### PR TITLE
Igor/add posted date for financial event list

### PR DESCRIPTION
**Pull request by Ig0r-M-magic42**
## Description
Adds PostedData data for AdjustmentEventList

## Type
- [x] Feature

## Tested
- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by Ig0r-M-magic42** [comment]
@georanma OR @georgeNanoWebGroup can you take a look at this PR

**Comment by georanma** [comment]
@Ig0r-M Im having one of my guys review me. On vacation and not good enough context at the moment. Looks fine otherwise.

**Comment by Ig0r-M-magic42** [comment]
Hello @georanma could you please provide ETA for this please.

**Comment by georanma** [comment]
@Ig0r-M merged.

**Comment by Ig0r-M-magic42** [comment]
Thanks @georanma, could you please create a tag version for these changes.

**Comment by georanma** [comment]
@Ig0r-M tagged and released

**Pull request merged**
